### ISSUE TITLE
When trying to retrieve a record using my own custom class, I get a JsonReaderException

### ISSUE THREAD

**Issue by nadcraker** [merccat/ServiceNowRESTClient#1]
Here is my class:
`    public class ServiceNowClientUser : ServiceNow.Record  
{
        [JsonProperty("u_default_group")]
        public string u_default_group { get; set; }
}`

Here is my calling code:
```
NetworkCredential nc = new NetworkCredential("user", "pass");
            TableAPIClient<ServiceNowClientUser> client = new TableAPIClient<ServiceNowClientUser>    
             ("sys_user", "myinst", nc);

            //Get a user
            string query = @"user_name=user123";
            IRestQueryResponse<ServiceNowClientUser> response = client.GetByQuery(query);
```

This line of code in ServiceNow.TableAPI.GetByQuery throws an exception:
`RESTQueryResponse<T> tmp = JsonConvert.DeserializeObject<RESTQueryResponse<T>>(response.RawJSON);`

The exception reads: 

> Additional information: Unexpected character encountered while parsing value: {. Path 'result[0].u_default_group', line 1, position 75.

**Comment by merccat** [comment]
Since that is a custom field you are trying to retrieve, I will need a little bit more info about it's definition and what is in it.  Unfortunately, in our instance we are not able to immediately replicate with our custom string fields, even if we do something wild like put json formatted data inside of our string field in service now.

Can you confirm that it is in fact a String type in your service now table definition and not a Reference type or something else?  Are you able able to provide what the response.RawJSON text looks like?  Thanks!

Kind Regards,
-Ryan

**Comment by nadcraker** [comment]
I actually got this to work by talking with one of our ServiceNow developers. I need to make a change in my class. I had to use dot notation to get at the field I wanted.

        [JsonProperty("u_default_group.name")]
        public string u_default_group { get; set; }

**Comment by merccat** [comment]
Oh awesome, I'm glad you got it sorted out.  

Yes, if it's a reference field, unless you want the reference itself, you'll want to use dot notation.  Note that I don't believe you will able to update the referenced field with dot notation, for that you would need to get the reference itself and update the referenced table directly.  There was actually a question along these lines (updated related records through dot notation) in the Service now community topic on this client so I will be experimenting with that some this weekend.

Speaking of which, have a great weekend!
